### ISSUE TITLE
'Repository is Empty'

### ISSUE THREAD

**Issue by alexbowers** [mmautner/github-email-thief#6]
Searching for my account, https://github.maxmautner.com/search/users?page=1&query=alexbowers, and clicking 'identify email', returns a 409 (conflict) error.

**Comment by mmautner** [comment]
Thanks Alex--looks like it's due to the first repository that's checked for commits doesn't have any.

Give me a sec and I'll handle that one

**Comment by mmautner** [comment]
Give it a refresh and all should be working now, thank you for the heads up :)

**Comment by alexbowers** [comment]
All is good
