### ISSUE TITLE
Dick move.

### ISSUE THREAD

**Issue by SchizoDuckie** [mmautner/github-email-thief#9]
Why do you want developers to get more spam?

**Comment by jaruba** [comment]
my email is compromised... oh noes..

![tumblr_lsb0syrh381qchjgt](https://cloud.githubusercontent.com/assets/1777923/12020980/b04c3662-ad8a-11e5-8a16-e8e10df536fb.gif)

**Comment by mmautner** [comment]
Take it up with Github @SchizoDuckie

**Comment by vankasteelj** [comment]
This has to be the stupidest tool ever. But then again : _WHY THE FUCK NOT?_ :smiley:
